### ISSUE TITLE
Postman folders inside collection

### ISSUE THREAD

**Issue by Ali-Fani** [rangav/thunder-imports#4]
After Update 1.1.0 added folders to collections, the folders from postman collections does not import

**Comment by rangav** [comment]
Hi @Ali-Fani can you attach a sample file that caused the error, without any sensitive information, I will verify it.

**Comment by Ali-Fani** [comment]
[Farawin Back-end reWrite.postman_collection.json.txt](https://github.com/rangav/thunder-imports/files/6403330/Farawin.Back-end.reWrite.postman_collection.json.txt)
![Screenshot 2021-04-30 110113](https://user-images.githubusercontent.com/23190191/116657290-68ec1d80-a9a3-11eb-800a-0565a85bfda1.png)

**Comment by rangav** [comment]
I will check and get back to you

**Comment by rangav** [comment]
Hi @Ali-Fani  it is working for me, what version of extension you have, latest is v1.1.0
![image](https://user-images.githubusercontent.com/8637550/116712614-efb4f080-a9cb-11eb-90d2-721cafaf32b0.png)

**Comment by Ali-Fani** [comment]
that is strange my extension was not the latest version thank you
