### ISSUE TITLE
Not active Query Parameters (Params) are not imported from Postman (Collection v2.1)

### ISSUE THREAD

**Issue by a-salimkhanov** [rangav/thunder-imports#6]
I see these params in the exported JSON file under `item.request.url.query` but they are not imported to Thunder Client.
Only active (checked) ones are imported.

Is there something I can do to import them? Or they're not supposed to be imported in the current version?

![Screenshot - 2021-06-06T194948 363 (1)](https://user-images.githubusercontent.com/61108267/120933170-91cda400-c701-11eb-928f-b05197b51e14.jpg)

**Comment by rangav** [comment]
Thanks for reporting the issue, you can look into the source code for imports
https://github.com/rangav/thunder-imports

**Comment by rangav** [comment]
Related issue 
https://github.com/rangav/thunder-client-support/issues/186

**Comment by rangav** [comment]
Or you can leave it to me, I will fix it in the next update.

**Comment by a-salimkhanov** [comment]
@rangav That would be great. Thanks a lot.
I'll wait for your update.

**Comment by rangav** [comment]
This is now fixed in v1.5.0
https://github.com/rangav/thunder-client-support/releases/tag/1.5.0
